@props(['services'=>collect(),'type'=>'quote','defaultMessage'=>'','submissionChannel'=>'web'])
@if(session('success'))
    <div class="notice-success" role="status">
        <strong>تم استلام طلبك.</strong>
        <span>{{ session('success') }}</span>
        @if(session('lead_whatsapp_url'))<a href="{{ session('lead_whatsapp_url') }}" target="_blank" rel="noopener">فتح الرسالة في واتساب</a>@endif
    </div>
@endif
<form method="POST" action="{{ route('leads.store') }}" class="lead-form" enctype="multipart/form-data" data-lead-form>
    @csrf
    <input type="hidden" name="type" value="{{ $type }}">
    <input type="hidden" name="submission_channel" value="{{ $submissionChannel }}">
    <div class="honeypot" aria-hidden="true"><label>الموقع <input type="text" name="website" tabindex="-1" autocomplete="off"></label></div>
    <div class="field-grid">
        <label class="form-field"><span>الاسم <em>اختياري</em></span><span class="form-control-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M4 21a8 8 0 0 1 16 0" fill="none" stroke="currentColor" stroke-width="1.7"/></svg><input type="text" name="name" value="{{ old('name') }}" maxlength="100" autocomplete="name" placeholder="اكتب اسمك"></span>@error('name')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>رقم الجوال <b>*</b></span><span class="form-control-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.3 3.8 9.6 8c.3.6.2 1.2-.3 1.6l-1.4 1.1a15 15 0 0 0 5.4 5.4l1.1-1.4c.4-.5 1.1-.6 1.6-.3l4.2 2.3c.6.3.9 1 .7 1.7l-.6 2.1c-.2.8-.9 1.3-1.7 1.4C9.8 22.1 1.9 14.2 2.1 5.4c0-.8.6-1.5 1.4-1.7l2.1-.6c.7-.2 1.4.1 1.7.7Z" fill="none" stroke="currentColor" stroke-width="1.7"/></svg><input type="tel" name="phone" value="{{ old('phone') }}" required maxlength="25" dir="ltr" inputmode="tel" autocomplete="tel" placeholder="05xxxxxxxx"></span>@error('phone')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>الخدمة المطلوبة <em>اختياري</em></span><span class="form-control-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5" fill="none" stroke="currentColor" stroke-width="1.7"/></svg><select name="service_id"><option value="">اختر الخدمة</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(old('service_id')==$service->id)>{{ $service->name }}</option>@endforeach</select></span>@error('service_id')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field"><span>الحي أو المنطقة <em>اختياري</em></span><span class="form-control-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s6-5.5 6-11a6 6 0 1 0-12 0c0 5.5 6 11 6 11Z" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="12" cy="10" r="2" fill="currentColor"/></svg><input type="text" name="area" value="{{ old('area') }}" maxlength="120" placeholder="مثال: حي النرجس"></span>@error('area')<small class="field-error">{{ $message }}</small>@enderror</label>
        <label class="form-field full-field"><span>المساحة التقريبية <em>اختياري</em></span><span class="form-control-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16v16H4zM4 9h4M9 4v4M20 15h-4M15 20v-4" fill="none" stroke="currentColor" stroke-width="1.7"/></svg><input type="number" name="area_size" value="{{ old('area_size') }}" min="1" max="1000000" step="0.01" inputmode="decimal" placeholder="مثال: 50 متر مربع"></span>@error('area_size')<small class="field-error">{{ $message }}</small>@enderror</label>
    </div>
    <fieldset class="contact-method-fieldset"><legend>كيف تفضّل أن نتواصل معك؟</legend><div class="radio-row"><label><input type="radio" name="preferred_contact" value="whatsapp" @checked(old('preferred_contact', $type === 'contact' ? 'whatsapp' : 'phone')==='whatsapp')><span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.6a8.5 8.5 0 0 1-12.6 7.5L3 20.4l1.3-4.7A8.5 8.5 0 1 1 20.5 11.6Z" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>واتساب</span></label><label><input type="radio" name="preferred_contact" value="phone" @checked(old('preferred_contact', $type === 'contact' ? 'whatsapp' : 'phone')==='phone')><span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4c3 8 5 10 13 13l-2 4C9 19 5 15 3 6Z" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>اتصال</span></label></div></fieldset>
    <label class="form-field"><span>تفاصيل الطلب <em>اختياري</em></span><textarea name="message" rows="4" maxlength="2000" placeholder="مثال: أرغب في مظلة لموقف سيارتين، والموقع جاهز للمعاينة">{{ old('message',$defaultMessage) }}</textarea>@error('message')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="upload-field"><span class="upload-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 6h16v13H4zM8 11l2-2 4 5 2-2 4 4M9 9h.01" fill="none" stroke="currentColor" stroke-width="1.7"/></svg></span><span><strong>أرفق صور الموقع</strong><em>اختياري — حتى 5 صور</em><small class="field-hint">JPG أو PNG أو WebP، بحد أقصى 5 ميجابايت للصورة.</small></span><input type="file" name="site_images[]" accept="image/jpeg,image/png,image/webp" multiple data-image-input><span class="upload-action">اختيار الصور</span>@error('site_images')<small class="field-error">{{ $message }}</small>@enderror @error('site_images.*')<small class="field-error">{{ $message }}</small>@enderror</label>
    <div class="lead-submit-row">
        <button class="button button-primary lead-submit" type="submit"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.6a8.5 8.5 0 0 1-12.6 7.5L3 20.4l1.3-4.7A8.5 8.5 0 1 1 20.5 11.6Z" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M8.3 7.3c.3-.4.7-.3.9.1l1 2c.2.4.1.7-.2 1l-.6.5c.7 1.4 1.8 2.5 3.2 3.2l.5-.6c.3-.3.6-.4 1-.2l2 1c.4.2.5.6.2.9-.5.8-1.3 1.2-2.2 1.1-3.4-.5-6.1-3.2-6.6-6.6-.1-.9.2-1.8.8-2.4Z" fill="currentColor"/></svg>{{ $submissionChannel === 'whatsapp' ? 'إكمال الطلب عبر واتساب' : 'إرسال الطلب' }}</button>
        <p class="form-privacy">بالإرسال توافق على <a href="{{ route('privacy') }}">سياسة الخصوصية</a>. لن تُعرض صورك للعامة.</p>
    </div>
</form>
