<!doctype html>
<html lang="ar-SA" dir="rtl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><link rel="icon" href="{{ asset('brand/mazallat-sawater-riyadh-icon.svg') }}" type="image/svg+xml"><title>{{ $title ?? 'لوحة التحكم' }} | {{ $siteSettings['site_name'] }}</title><style id="theme-palette">{!! app(\App\Support\ThemePalette::class)->css($siteSettings) !!}</style>@vite(['resources/css/app.css','resources/js/app.js'])@livewireStyles</head>
<body class="admin-body">
<div class="admin-shell">
    <aside class="admin-sidebar"><a class="brand admin-brand" href="{{ route('admin.dashboard') }}"><x-site-logo class="admin-brand-logo" :alt="$siteSettings['site_name']" /><strong class="sr-only">إدارة الموقع</strong></a><nav><a @class(['active'=>request()->routeIs('admin.dashboard')]) href="{{ route('admin.dashboard') }}">نظرة عامة</a><a @class(['active'=>request()->routeIs('admin.leads')]) href="{{ route('admin.leads') }}">طلبات العملاء</a>@foreach(\App\Support\AdminContent::all() as $key=>$item)<a @class(['active'=>request('type')===$key]) href="{{ route('admin.content.index',$key) }}">{{ $item['label'] }}</a>@endforeach<a @class(['active'=>request()->routeIs('admin.settings')]) href="{{ route('admin.settings') }}">إعدادات النشاط</a><a href="{{ route('admin.settings') }}#appearance">المظهر والألوان</a></nav></aside>
    <div class="admin-main"><header class="admin-topbar"><div><button type="button" class="admin-menu" data-admin-menu aria-label="فتح قائمة الإدارة">☰</button><h1>{{ $title ?? 'لوحة التحكم' }}</h1></div><div><a href="{{ route('home') }}" target="_blank">عرض الموقع</a><form method="POST" action="{{ route('admin.logout') }}">@csrf<button type="submit">خروج</button></form></div></header><main class="admin-content">@if(session('success'))<div class="notice-success">{{ session('success') }}</div>@endif{{ $slot }}</main></div>
</div>@livewireScripts
</body></html>
