<?php

return [
    'launch_services' => [
        'مظلات PVC',
        'مظلات الشد الإنشائي',
        'سواتر حديد',
        'سواتر خشب',
        'سواتر قماش',
        'الخيام',
        'بيوت الشعر',
        'الهناجر',
        'الساندوتش بنل',
        'البرجولات',
        'الجلسات الشتوية',
        'جلسات زجاجية',
        'الشترات والأبواب الإلكترونية',
        'الشترات',
        'النوافذ',
        'الأبواب الكهربائية',
    ],
    'service_taxonomy' => [
        'المظلات' => ['مظلات PVC', 'مظلات الشد الإنشائي'],
        'السواتر' => ['سواتر حديد', 'سواتر خشب', 'سواتر قماش'],
        'الخيام وبيوت الشعر' => ['الخيام', 'بيوت الشعر'],
        'الهناجر والإنشاءات' => ['الهناجر', 'الساندوتش بنل'],
        'البرجولات والجلسات' => ['البرجولات', 'الجلسات الشتوية', 'جلسات زجاجية'],
        'الشترات والنوافذ والأبواب' => ['الشترات والأبواب الإلكترونية', 'الشترات', 'النوافذ', 'الأبواب الكهربائية'],
    ],
    'service_featured_images' => [
        'مظلات PVC' => 'services/shadanshai.webp',
        'مظلات الشد الإنشائي' => 'services/tensile-structure-shade-riyadh.webp',
        'سواتر حديد' => 'services/sawater-riyadh.webp',
        'سواتر خشب' => 'services/sawater-riyadh.webp',
        'سواتر قماش' => 'services/sawater-riyadh.webp',
        'الخيام' => 'services/tents-bayt-alshaar-riyadh.webp',
        'بيوت الشعر' => 'services/tents-bayt-alshaar-riyadh.webp',
        'البرجولات' => 'services/pergolas-riyadh.webp',
        'الجلسات الشتوية' => 'services/geometric-tensile-shade-riyadh.webp',
        'جلسات زجاجية' => 'services/geometric-tensile-shade-riyadh.webp',
    ],
    'article_featured_images' => [
        'أسعار مظلات السيارات في الرياض والعوامل التي تحدد التكلفة' => 'services/shadanshai.webp',
        'أفضل أنواع مظلات السيارات المناسبة لأجواء الرياض' => 'services/shadanshai.webp',
        'الفرق بين مظلات PVC والبولي إيثيلين' => 'services/shadanshai.webp',
        'أسعار السواتر في الرياض حسب الخامة والتصميم' => 'services/sawater-riyadh.webp',
        'سواتر الحديد أم بديل الخشب: كيف تختار؟' => 'services/sawater-riyadh.webp',
        'أنواع البرجولات المناسبة للحدائق والجلسات الخارجية' => 'services/pergolas-riyadh.webp',
        'استخدامات الساندوتش بانل في الغرف والملاحق والمستودعات' => 'services/hangars-riyadh.webp',
        'كيف تختار مقاول مظلات وسواتر في الرياض؟' => 'services/shadanshai.webp',
        'متى تحتاج مظلتك إلى صيانة أو تغيير القماش؟' => 'services/shadanshai.webp',
        'الفرق بين المظلات المعلقة والهرمية والشد الإنشائي' => 'services/tensile-structure-shade-riyadh.webp',
    ],
    'about_image' => 'about/aboutus.webp',
    'header_image' => 'brand/hereo.webp',
    'fallback' => [
        'site_name' => 'مظلات وسواتر الرياض',
        'phone_display' => '+966 56 206 6426',
        'phone_e164' => '+966562066426',
        'phone_tel' => 'tel:+966562066426',
        'whatsapp_url' => 'https://wa.me/966562066426',
        'address' => 'الرياض، وسط الرياض، المملكة العربية السعودية',
        'city' => 'الرياض',
        'country' => 'المملكة العربية السعودية',
        'locale' => 'ar_SA',
        'search_console_verification' => '',
        'ga_measurement_id' => '',
        'logo_url' => '',
    ],
];
