<?php

return [
    'launch_services' => [
        'مظلات PVC',
        'مظلات الشد الإنشائي',
        'سواتر حديد',
        'سواتر خشب',
        'سواتر قماش',
        'الخيام',
        'بيوت الشعر',
        'الهناجر',
        'الساندوتش بنل',
        'البرجولات',
        'جلسات زجاجية',
        'الشترات',
        'النوافذ',
        'الأبواب الكهربائية',
    ],
    'service_taxonomy' => [
        'المظلات' => ['مظلات PVC', 'مظلات الشد الإنشائي'],
        'السواتر' => ['سواتر حديد', 'سواتر خشب', 'سواتر قماش'],
        'الخيام وبيوت الشعر' => ['الخيام', 'بيوت الشعر'],
        'الهناجر والإنشاءات' => ['الهناجر', 'الساندوتش بنل'],
        'البرجولات والجلسات' => ['البرجولات', 'جلسات زجاجية'],
        'الشترات والنوافذ والأبواب' => ['الشترات', 'النوافذ', 'الأبواب الكهربائية'],
    ],
    'service_featured_images' => [
        'مظلات PVC' => 'services/mazallat-riyadh.webp',
        'مظلات الشد الإنشائي' => 'services/mazallat-riyadh.webp',
        'سواتر حديد' => 'services/sawater-riyadh.webp',
        'سواتر خشب' => 'services/sawater-riyadh.webp',
        'سواتر قماش' => 'services/sawater-riyadh.webp',
        'الخيام' => 'services/tents-bayt-alshaar-riyadh.webp',
        'بيوت الشعر' => 'services/tents-bayt-alshaar-riyadh.webp',
        'الهناجر' => 'services/hangars-riyadh.webp',
        'الساندوتش بنل' => 'services/hangars-riyadh.webp',
        'البرجولات' => 'services/pergolas-riyadh.webp',
        'جلسات زجاجية' => 'services/pergolas-riyadh.webp',
        'الشترات' => 'services/shutters-windows-doors-riyadh.webp',
        'النوافذ' => 'services/shutters-windows-doors-riyadh.webp',
        'الأبواب الكهربائية' => 'services/shutters-windows-doors-riyadh.webp',
    ],
    'about_image' => 'about/aboutus.webp',
    'fallback' => [
        'site_name' => 'مظلات وسواتر الرياض',
        'phone_display' => '+966 56 206 6426',
        'phone_e164' => '+966562066426',
        'phone_tel' => 'tel:+966562066426',
        'whatsapp_url' => 'https://wa.me/966562066426',
        'address' => 'الرياض، وسط الرياض، المملكة العربية السعودية',
        'city' => 'الرياض',
        'country' => 'المملكة العربية السعودية',
        'locale' => 'ar_SA',
        'search_console_verification' => '',
        'ga_measurement_id' => '',
        'logo_url' => '',
    ],
];
